package com.squad.questions;

import com.squad.structure.Options;
import com.squad.structure.Question;

import java.util.ArrayList;
import java.util.Random;

public class RandomQuestions {

    public static ArrayList<Question> getPrimaryQuestion() {
        ArrayList<Question> list = new ArrayList<>();
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTejBLKBcww2McB3ZwMFKgHydrhuHV1OTL2UO7_6CG56tULhW7Y", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSf8cnAgl_OxcPcGLv7SHBX9tuvd-mUOTgM16hslVZ4SUXuwQbm", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRVPa7TRMyNubIpc_-sd7oMN8zmW_sSAc2Z3z9vdTpDl6qRKk5F","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQy28NtLEXuc1R4iSFELIn22irSRf5NmwMRzXv5enj_zatvVVF7"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0qVPu8s0-BfHnUX_7QGEpmRV8Tevv83Z1-18bLrqCEbnXRQ0P", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRxsrkRuL6zl7TRacZSHSMjger-7yANllrjVmhLyeF5U4gR1DH1", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRdXwOdxV25ekvjX0lclJIOhGVtfmRUB2rJKoKLTI_6NBkzv-jJ","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRPVDC9bBYLbQZWQtWERmLrR2sTaSi-9WfWCBOWVRDgr5p2xX5r", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSUSVT9Vz01K2ctgpbBmbvpvlRVBVAW9BdWLFJpBD_APt1TxvEV","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSGwRpm4mLAVVo6yE022qdXV449NXZTOGIblREgPD61fRKheisu", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRlJl8UaeaNDWCCW8LD-lN-kIkPpG-Tuz-UrttLd8ImTG95wxWp","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPlysxCVBn8E8csNokguEleO7olhopHt6mopvADEA5aSakQHID"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTsmh3koRcBDEPHo8IJtYdwFduDM6sip5oo2JNBO1RxijRUBZOt", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSAI6_kWG2_6MT-llVgOOuWNvEY8YFbLQt7SaqIFcN7AOMDtZvA", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRGbeNKK3oopDw3sG-Ys1Z2zblyrDtoFaWJO82g1MOJaz07eFv4","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ-3-3Zbb7ZnnB9emehAnAyK2CkhM6QlKGVBs6_Eo5UcSgshftk"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRE9rbrY-61foXI78O97WVCM68H5M9pmT1SEAgskM3wLOEtRw9v", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfmwLbJGESD-3kg1eMet3TPLf6bwVrpvjw_Pct4PWi1Nbt-59s", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxJZwoHTAhEBaQHeFrlxVNQjZZd5sCPyJc6T-d0MlQocT9zPUT","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTCS3ogXLvT0B92XuU286G74S7bq33R5LB6TjQCO2o5lVmL1-9E"), false));

        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTejBLKBcww2McB3ZwMFKgHydrhuHV1OTL2UO7_6CG56tULhW7Y", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSf8cnAgl_OxcPcGLv7SHBX9tuvd-mUOTgM16hslVZ4SUXuwQbm", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRVPa7TRMyNubIpc_-sd7oMN8zmW_sSAc2Z3z9vdTpDl6qRKk5F","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQy28NtLEXuc1R4iSFELIn22irSRf5NmwMRzXv5enj_zatvVVF7"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0qVPu8s0-BfHnUX_7QGEpmRV8Tevv83Z1-18bLrqCEbnXRQ0P", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRxsrkRuL6zl7TRacZSHSMjger-7yANllrjVmhLyeF5U4gR1DH1", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRdXwOdxV25ekvjX0lclJIOhGVtfmRUB2rJKoKLTI_6NBkzv-jJ","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRPVDC9bBYLbQZWQtWERmLrR2sTaSi-9WfWCBOWVRDgr5p2xX5r", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSUSVT9Vz01K2ctgpbBmbvpvlRVBVAW9BdWLFJpBD_APt1TxvEV","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSGwRpm4mLAVVo6yE022qdXV449NXZTOGIblREgPD61fRKheisu", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRlJl8UaeaNDWCCW8LD-lN-kIkPpG-Tuz-UrttLd8ImTG95wxWp","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPlysxCVBn8E8csNokguEleO7olhopHt6mopvADEA5aSakQHID"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTsmh3koRcBDEPHo8IJtYdwFduDM6sip5oo2JNBO1RxijRUBZOt", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSAI6_kWG2_6MT-llVgOOuWNvEY8YFbLQt7SaqIFcN7AOMDtZvA", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRGbeNKK3oopDw3sG-Ys1Z2zblyrDtoFaWJO82g1MOJaz07eFv4","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ-3-3Zbb7ZnnB9emehAnAyK2CkhM6QlKGVBs6_Eo5UcSgshftk"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRE9rbrY-61foXI78O97WVCM68H5M9pmT1SEAgskM3wLOEtRw9v", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfmwLbJGESD-3kg1eMet3TPLf6bwVrpvjw_Pct4PWi1Nbt-59s", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxJZwoHTAhEBaQHeFrlxVNQjZZd5sCPyJc6T-d0MlQocT9zPUT","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTCS3ogXLvT0B92XuU286G74S7bq33R5LB6TjQCO2o5lVmL1-9E"), false));

        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTejBLKBcww2McB3ZwMFKgHydrhuHV1OTL2UO7_6CG56tULhW7Y", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSf8cnAgl_OxcPcGLv7SHBX9tuvd-mUOTgM16hslVZ4SUXuwQbm", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRVPa7TRMyNubIpc_-sd7oMN8zmW_sSAc2Z3z9vdTpDl6qRKk5F","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQy28NtLEXuc1R4iSFELIn22irSRf5NmwMRzXv5enj_zatvVVF7"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0qVPu8s0-BfHnUX_7QGEpmRV8Tevv83Z1-18bLrqCEbnXRQ0P", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRxsrkRuL6zl7TRacZSHSMjger-7yANllrjVmhLyeF5U4gR1DH1", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRdXwOdxV25ekvjX0lclJIOhGVtfmRUB2rJKoKLTI_6NBkzv-jJ","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRPVDC9bBYLbQZWQtWERmLrR2sTaSi-9WfWCBOWVRDgr5p2xX5r", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSUSVT9Vz01K2ctgpbBmbvpvlRVBVAW9BdWLFJpBD_APt1TxvEV","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSGwRpm4mLAVVo6yE022qdXV449NXZTOGIblREgPD61fRKheisu", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRlJl8UaeaNDWCCW8LD-lN-kIkPpG-Tuz-UrttLd8ImTG95wxWp","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPlysxCVBn8E8csNokguEleO7olhopHt6mopvADEA5aSakQHID"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTsmh3koRcBDEPHo8IJtYdwFduDM6sip5oo2JNBO1RxijRUBZOt", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSAI6_kWG2_6MT-llVgOOuWNvEY8YFbLQt7SaqIFcN7AOMDtZvA", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRGbeNKK3oopDw3sG-Ys1Z2zblyrDtoFaWJO82g1MOJaz07eFv4","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ-3-3Zbb7ZnnB9emehAnAyK2CkhM6QlKGVBs6_Eo5UcSgshftk"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRE9rbrY-61foXI78O97WVCM68H5M9pmT1SEAgskM3wLOEtRw9v", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfmwLbJGESD-3kg1eMet3TPLf6bwVrpvjw_Pct4PWi1Nbt-59s", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxJZwoHTAhEBaQHeFrlxVNQjZZd5sCPyJc6T-d0MlQocT9zPUT","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTCS3ogXLvT0B92XuU286G74S7bq33R5LB6TjQCO2o5lVmL1-9E"), false));

        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTejBLKBcww2McB3ZwMFKgHydrhuHV1OTL2UO7_6CG56tULhW7Y", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSf8cnAgl_OxcPcGLv7SHBX9tuvd-mUOTgM16hslVZ4SUXuwQbm", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRVPa7TRMyNubIpc_-sd7oMN8zmW_sSAc2Z3z9vdTpDl6qRKk5F","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQy28NtLEXuc1R4iSFELIn22irSRf5NmwMRzXv5enj_zatvVVF7"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0qVPu8s0-BfHnUX_7QGEpmRV8Tevv83Z1-18bLrqCEbnXRQ0P", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRxsrkRuL6zl7TRacZSHSMjger-7yANllrjVmhLyeF5U4gR1DH1", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRdXwOdxV25ekvjX0lclJIOhGVtfmRUB2rJKoKLTI_6NBkzv-jJ","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRPVDC9bBYLbQZWQtWERmLrR2sTaSi-9WfWCBOWVRDgr5p2xX5r", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSUSVT9Vz01K2ctgpbBmbvpvlRVBVAW9BdWLFJpBD_APt1TxvEV","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSGwRpm4mLAVVo6yE022qdXV449NXZTOGIblREgPD61fRKheisu", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRlJl8UaeaNDWCCW8LD-lN-kIkPpG-Tuz-UrttLd8ImTG95wxWp","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPlysxCVBn8E8csNokguEleO7olhopHt6mopvADEA5aSakQHID"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTsmh3koRcBDEPHo8IJtYdwFduDM6sip5oo2JNBO1RxijRUBZOt", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSAI6_kWG2_6MT-llVgOOuWNvEY8YFbLQt7SaqIFcN7AOMDtZvA", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRGbeNKK3oopDw3sG-Ys1Z2zblyrDtoFaWJO82g1MOJaz07eFv4","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ-3-3Zbb7ZnnB9emehAnAyK2CkhM6QlKGVBs6_Eo5UcSgshftk"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRE9rbrY-61foXI78O97WVCM68H5M9pmT1SEAgskM3wLOEtRw9v", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfmwLbJGESD-3kg1eMet3TPLf6bwVrpvjw_Pct4PWi1Nbt-59s", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxJZwoHTAhEBaQHeFrlxVNQjZZd5sCPyJc6T-d0MlQocT9zPUT","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTCS3ogXLvT0B92XuU286G74S7bq33R5LB6TjQCO2o5lVmL1-9E"), false));

        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTejBLKBcww2McB3ZwMFKgHydrhuHV1OTL2UO7_6CG56tULhW7Y", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSf8cnAgl_OxcPcGLv7SHBX9tuvd-mUOTgM16hslVZ4SUXuwQbm", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRVPa7TRMyNubIpc_-sd7oMN8zmW_sSAc2Z3z9vdTpDl6qRKk5F","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQy28NtLEXuc1R4iSFELIn22irSRf5NmwMRzXv5enj_zatvVVF7"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0qVPu8s0-BfHnUX_7QGEpmRV8Tevv83Z1-18bLrqCEbnXRQ0P", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRxsrkRuL6zl7TRacZSHSMjger-7yANllrjVmhLyeF5U4gR1DH1", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRdXwOdxV25ekvjX0lclJIOhGVtfmRUB2rJKoKLTI_6NBkzv-jJ","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRPVDC9bBYLbQZWQtWERmLrR2sTaSi-9WfWCBOWVRDgr5p2xX5r", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSUSVT9Vz01K2ctgpbBmbvpvlRVBVAW9BdWLFJpBD_APt1TxvEV","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSGwRpm4mLAVVo6yE022qdXV449NXZTOGIblREgPD61fRKheisu", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRlJl8UaeaNDWCCW8LD-lN-kIkPpG-Tuz-UrttLd8ImTG95wxWp","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPlysxCVBn8E8csNokguEleO7olhopHt6mopvADEA5aSakQHID"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTsmh3koRcBDEPHo8IJtYdwFduDM6sip5oo2JNBO1RxijRUBZOt", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSAI6_kWG2_6MT-llVgOOuWNvEY8YFbLQt7SaqIFcN7AOMDtZvA", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRGbeNKK3oopDw3sG-Ys1Z2zblyrDtoFaWJO82g1MOJaz07eFv4","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ-3-3Zbb7ZnnB9emehAnAyK2CkhM6QlKGVBs6_Eo5UcSgshftk"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRE9rbrY-61foXI78O97WVCM68H5M9pmT1SEAgskM3wLOEtRw9v", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfmwLbJGESD-3kg1eMet3TPLf6bwVrpvjw_Pct4PWi1Nbt-59s", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxJZwoHTAhEBaQHeFrlxVNQjZZd5sCPyJc6T-d0MlQocT9zPUT","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTCS3ogXLvT0B92XuU286G74S7bq33R5LB6TjQCO2o5lVmL1-9E"), false));

        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTejBLKBcww2McB3ZwMFKgHydrhuHV1OTL2UO7_6CG56tULhW7Y", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSf8cnAgl_OxcPcGLv7SHBX9tuvd-mUOTgM16hslVZ4SUXuwQbm", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRVPa7TRMyNubIpc_-sd7oMN8zmW_sSAc2Z3z9vdTpDl6qRKk5F","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQy28NtLEXuc1R4iSFELIn22irSRf5NmwMRzXv5enj_zatvVVF7"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0qVPu8s0-BfHnUX_7QGEpmRV8Tevv83Z1-18bLrqCEbnXRQ0P", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRxsrkRuL6zl7TRacZSHSMjger-7yANllrjVmhLyeF5U4gR1DH1", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRdXwOdxV25ekvjX0lclJIOhGVtfmRUB2rJKoKLTI_6NBkzv-jJ","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRPVDC9bBYLbQZWQtWERmLrR2sTaSi-9WfWCBOWVRDgr5p2xX5r", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSUSVT9Vz01K2ctgpbBmbvpvlRVBVAW9BdWLFJpBD_APt1TxvEV","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSGwRpm4mLAVVo6yE022qdXV449NXZTOGIblREgPD61fRKheisu", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRlJl8UaeaNDWCCW8LD-lN-kIkPpG-Tuz-UrttLd8ImTG95wxWp","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPlysxCVBn8E8csNokguEleO7olhopHt6mopvADEA5aSakQHID"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTsmh3koRcBDEPHo8IJtYdwFduDM6sip5oo2JNBO1RxijRUBZOt", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSAI6_kWG2_6MT-llVgOOuWNvEY8YFbLQt7SaqIFcN7AOMDtZvA", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRGbeNKK3oopDw3sG-Ys1Z2zblyrDtoFaWJO82g1MOJaz07eFv4","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ-3-3Zbb7ZnnB9emehAnAyK2CkhM6QlKGVBs6_Eo5UcSgshftk"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRE9rbrY-61foXI78O97WVCM68H5M9pmT1SEAgskM3wLOEtRw9v", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfmwLbJGESD-3kg1eMet3TPLf6bwVrpvjw_Pct4PWi1Nbt-59s", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxJZwoHTAhEBaQHeFrlxVNQjZZd5sCPyJc6T-d0MlQocT9zPUT","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTCS3ogXLvT0B92XuU286G74S7bq33R5LB6TjQCO2o5lVmL1-9E"), false));

        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTejBLKBcww2McB3ZwMFKgHydrhuHV1OTL2UO7_6CG56tULhW7Y", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSf8cnAgl_OxcPcGLv7SHBX9tuvd-mUOTgM16hslVZ4SUXuwQbm", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRVPa7TRMyNubIpc_-sd7oMN8zmW_sSAc2Z3z9vdTpDl6qRKk5F","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQy28NtLEXuc1R4iSFELIn22irSRf5NmwMRzXv5enj_zatvVVF7"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0qVPu8s0-BfHnUX_7QGEpmRV8Tevv83Z1-18bLrqCEbnXRQ0P", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRxsrkRuL6zl7TRacZSHSMjger-7yANllrjVmhLyeF5U4gR1DH1", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRdXwOdxV25ekvjX0lclJIOhGVtfmRUB2rJKoKLTI_6NBkzv-jJ","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPdX46EnRyVeRSegKJ4VJ49HuCBNsMHKpUBltGD4Vi1BqsyV67", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRPVDC9bBYLbQZWQtWERmLrR2sTaSi-9WfWCBOWVRDgr5p2xX5r", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSUSVT9Vz01K2ctgpbBmbvpvlRVBVAW9BdWLFJpBD_APt1TxvEV","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQmMbQdyaPDzkg6Bzc5kskd2Esc_Q5b_6IlbFZ0zDFbmI_zn1IX", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSGwRpm4mLAVVo6yE022qdXV449NXZTOGIblREgPD61fRKheisu", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRlJl8UaeaNDWCCW8LD-lN-kIkPpG-Tuz-UrttLd8ImTG95wxWp","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPlysxCVBn8E8csNokguEleO7olhopHt6mopvADEA5aSakQHID"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTsmh3koRcBDEPHo8IJtYdwFduDM6sip5oo2JNBO1RxijRUBZOt", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSAI6_kWG2_6MT-llVgOOuWNvEY8YFbLQt7SaqIFcN7AOMDtZvA", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRGbeNKK3oopDw3sG-Ys1Z2zblyrDtoFaWJO82g1MOJaz07eFv4","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ-3-3Zbb7ZnnB9emehAnAyK2CkhM6QlKGVBs6_Eo5UcSgshftk"), false));
        list.add(new Question("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRE9rbrY-61foXI78O97WVCM68H5M9pmT1SEAgskM3wLOEtRw9v", new Options("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQfmwLbJGESD-3kg1eMet3TPLf6bwVrpvjw_Pct4PWi1Nbt-59s", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxJZwoHTAhEBaQHeFrlxVNQjZZd5sCPyJc6T-d0MlQocT9zPUT","https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTCS3ogXLvT0B92XuU286G74S7bq33R5LB6TjQCO2o5lVmL1-9E"), false));

        return list;
    }

    static int getRandomQuestionFromList(ArrayList<Question> list) {
        Random random = new Random();
        return random.nextInt(list.size());
    }

}
